### ISSUE TITLE
error on playing song

### ISSUE THREAD

**Issue by anntnzrb** [aloussase/qobra#1]
loaded a folder containing one `.mp3` song:
```sh
$ ls ~/downloads/musc 
'Dr.Disrespect - Gillette (The Best A Man Can Get) By 199X [LINK IN DESC]-9fWxCIi5PIw.mp3' 
```
```sh
$ qobra ~/downloads/musc
```

error:
```sh
Traceback (most recent call last): 
  File "/usr/local/bin/qobra", line 72, in <module> 
    curses.wrapper(run) 
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper 
    return func(stdscr, *args, **kwds) 
  File "/usr/local/bin/qobra", line 57, in run 
    f.handle_input(stdscr, player) 
  File "/usr/local/bin/qobra_functions.py", line 76, in handle_input 
    player.play() 
  File "/usr/local/bin/qobra_player.py", line 157, in play 
    popen = Popen(['mpg123', path], stderr=PIPE) 
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__ 
    self._execute_child(args, executable, preexec_fn, close_fds, 
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child 
    raise child_exception_type(errno_num, err_msg, err_filename) 
FileNotFoundError: [Errno 2] No such file or directory: 'mpg123' 
```

**Comment by anntnzrb** [comment]
installing `mpg123` solved this
